package com.example.jetnote.combat.badLanguageWords

val listOfBadSpanishWords = arrayOf(
    "Puta madre",
    "a tomar por saco",
    "anda a cagar",
    "apestar",
    "bastardo",
    "basura",
    "bicho",
    "burro",
    "cabron",
    "cabrón",
    "cacorro",
    "cagar",
    "calientapollas",
    "capullo",
    "cara de culo",
    "cara de monda",
    "carajo",
    "chapero",
    "chichi",
    "chimba",
    "chingar",
    "chocho",
    "chupame la polla",
    "chupamedias",
    "chupamela",
    "chupar",
    "chúpame la pija",
    "cipote",
    "coger",
    "cojonazos",
    "cojones",
    "come mierda y muere",
    "coño",
    "culiao",
    "culo",
    "de puta madre",
    "estúpido",
    "follar",
    "forro",
    "gilipollas",
    "gonorrea",
    "guarra",
    "hijo de perra",
    "hijo de puta",
    "hijueputa",
    "hostia",
    "huevo",
    "huevos",
    "huevón",
    "idiota",
    "imbécil",
    "jode",
    "joder",
    "joder ",
    "joto",
    "jódete",
    "la concha de tu madre",
    "la hostia",
    "la madre que te parió",
    "lame botas",
    "loco",
    "los cojones",
    "maldito",
    "malparido",
    "mamahuevo",
    "mamón",
    "marica",
    "maricon",
    "mariconazo",
    "maricón",
    "mariquita",
    "me cago en la hostia",
    "me cago en ti",
    "mierda",
    "mongolo",
    "métetelo por el culo",
    "nabo",
    "no me jodas",
    "no me jodás",
    "no seas gilipollas",
    "pajero",
    "payaso",
    "pelos de los huevos",
    "pelotas",
    "pelotudo",
    "pendejo",
    "percanta",
    "perro",
    "pichacorta",
    "pinche",
    "piruja",
    "polla",
    "pollas en vinagre",
    "puta",
    "puto",
    "que te den",
    "que te jodan",
    "qué cabrón",
    "qué te jodan",
    "rabo",
    "raja",
    "soplapollas",
    "tarado",
    "tonto",
    "tonto del culo",
    "tontopollas",
    "trompada",
    "un putero",
    "verga",
    "vete a la mierda",
    "vete a la verga",
    "vete al demonio",
    "vete al infierno",
    "zorra",
    "zunga",
    "a tomar por culo"
    )