package com.example.jetnote.combat.badLanguageWords

val listOfBadGermanWords = arrayOf(
    "abschaum",
    "affenschwanz",
    "ah du schwein",
    "alter muschi",
    "alter wichser",
    "am blitz geleckt haben",
    "analritter",
    "arsch",
    "arschficker",
    "arschfotze",
    "arschgeige",
    "arschgesicht",
    "arschkeks",
    "arschkriecher",
    "arschlecker",
    "arschloch",
    "auberfeiger",
    "aufgeilen",
    "backpfeifengesicht",
    "bastard",
    "bimbo",
    "bloede kuh",
    "blutige sau",
    "blvde fotze",
    "blöde gans",
    "blöde stinkpot",
    "blödmann",
    "blödsinn",
    "bonze",
    "bratze",
    "bruchbude",
    "bumsen",
    "das arschloch",
    "das ist mir scheißegal",
    "das miststück",
    "das schwein",
    "depp",
    "der dreckskerl",
    "der fotzenlecker",
    "der mist",
    "der mistkerl",
    "der wichser",
    "die drecksau",
    "die sau",
    "die verarsche",
    "donnerwetter",
    "dreckige hure",
    "drecksack",
    "drecksau",
    "dreckskerl",
    "drecksnest",
    "du Hurensohn",
    "du bastard",
    "du blöde kuh",
    "du fickfehler",
    "du hurensohn",
    "du kannst mich mal",
    "du sau",
    "du schwein",
    "du weichei",
    "dummbatz",
    "dumme",
    "dumme kuh",
    "dumme nuss",
    "dummkopf",
    "dumpfbacke",
    "dödel",
    "erarschen",
    "fahr zur holle",
    "feigling",
    "fick",
    "fick deine mutter",
    "fick dich",
    "fick dich arschloch",
    "fick dich in knie",
    "ficke",
    "ficken",
    "ficker",
    "filzlaus",
    "flachwichser",
    "flittchen",
    "fotze",
    "fratze",
    "geh zum teufel",
    "gottverdammt",
    "hackfresse",
    "halt deinen mund",
    "halt die fotze",
    "halt die klappe",
    "hat jemand dir ins gehirn geschissen",
    "hirnrissig",
    "homo",
    "hosenscheisser",
    "huhrensohn",
    "hure",
    "huren",
    "huren sohn",
    "hurensohn",
    "ich ficke deine mutter",
    "ich ficke deine schwester",
    "ich hasse dich",
    "ich will dich ficken",
    "ich will ficken",
    "idiot",
    "ische",
    "kackbratze",
    "kacke",
    "kacken",
    "kackwurst",
    "kampflesbe",
    "kanake",
    "kimme",
    "klugscheißer",
    "küss meinen arsch",
    "lech mien arsch",
    "leck mich",
    "leck mich am arsch",
    "lesbe",
    "lick",
    "lms",
    "lusche",
    "lutsch mein’ schwanz",
    "lutschen",
    "lutsch’ meine eier",
    "lümmel",
    "milf",
    "mist",
    "miststück",
    "morgenlatte",
    "mufti",
    "muschi",
    "muschi lecker",
    "mutterficker",
    "möpse",
    "möse",
    "nackt",
    "neger",
    "nigger",
    "nippel",
    "nutte",
    "ohne scheiß",
    "onanieren",
    "orgasmus",
    "penis",
    "penner",
    "pimmel",
    "pimpern",
    "pinkeln",
    "pisse",
    "pissen",
    "pisser",
    "popel",
    "poppen",
    "porno",
    "puff",
    "quatsch",
    "reudig",
    "rosette",
    "saugen",
    "schabracke",
    "scheiss",
    "scheissdreck",
    "scheisse",
    "scheissekopf",
    "scheissen",
    "scheisser",
    "scheisskerl",
    "scheisskopf",
    "scheiße",
    "schiesser",
    "schlampe",
    "schnackeln",
    "schnoodle noodle",
    "schwanz",
    "schwanzlutscher",
    "schweinebacke",
    "schweinehund",
    "schwuchtel",
    "schwuchtl",
    "shaisa",
    "sheisse",
    "sohn einer hündin",
    "spasti",
    "spießig",
    "spinnen",
    "spinner",
    "spinnst",
    "teufel",
    "tittchen",
    "titten",
    "trottel",
    "verdammt",
    "verdammte scheiße",
    "verdammter",
    "verdammter Scheiß",
    "verfluchter",
    "verpiss dich",
    "verrückter mann",
    "vollidiot",
    "vollpfosten",
    "vollscheißen",
    "volltrottel",
    "vögeln",
    "was zum teufel",
    "was zur hölle",
    "weichei",
    "wichse",
    "wichsen",
    "wichser",
    "witzbold",
    "zicke",
    "zur holle mit dir",
)
