package com.example.jetnote.cons.bad_words

val badEnglish = arrayOf(
    "2 girls 1 cup",
    "2g1c",
    "4r5e",
    "5h1t",
    "5hit",
    "a$$",
    "a$\$hole",
    "a2m",
    "a54",
    "a55",
    "a55hole",
    "a_s_s",
    "aeolus",
    "ahole",
    "alabama hot pocket",
    "alaskan pipeline",
    "anal",
    "anal impaler",
    "anal leakage",
    "analannie",
    "analprobe",
    "analsex",
    "anilingus",
    "anus",
    "apeshit",
    "ar5e",
    "areola",
    "areole",
    "arian",
    "arrse",
    "arse",
    "arsehole",
    "aryan",
    "ass",
    "ass fuck",
    "ass hole",
    "ass-fucker",
    "ass-hat",
    "ass-jabber",
    "ass-pirate",
    "assault",
    "assbag",
    "assbagger",
    "assbandit",
    "assbang",
    "assbanged",
    "assbanger",
    "assbangs",
    "assbite",
    "assblaster",
    "assclown",
    "asscock",
    "asscracker",
    "asses",
    "assface",
    "assfaces",
    "assfuck",
    "assfucker",
    "assfukka",
    "assgoblin",
    "assh0le",
    "asshat",
    "asshead",
    "assho1e",
    "asshole",
    "assholes",
    "asshopper",
    "asshore",
    "assjacker",
    "assjockey",
    "asskiss",
    "asskisser",
    "assklown",
    "asslick",
    "asslicker",
    "asslover",
    "assman",
    "assmaster",
    "assmonkey",
    "assmucus",
    "assmunch",
    "assmuncher",
    "assnigger",
    "asspacker",
    "asspirate",
    "asspuppies",
    "assranger",
    "assshit",
    "assshole",
    "asssucker",
    "asswad",
    "asswhole",
    "asswhore",
    "asswipe",
    "asswipes",
    "auto erotic",
    "autoerotic",
    "axwound",
    "azazel",
    "azz",
    "b!tch",
    "b00bs",
    "b17ch",
    "b1tch",
    "babe",
    "babeland",
    "babes",
    "baby batter",
    "baby juice",
    "badfuck",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "balllicker",
    "balls",
    "ballsack",
    "bampot",
    "bang",
    "bang (one's) box",
    "bangbros",
    "banger",
    "banging",
    "bareback",
    "barely legal",
    "barenaked",
    "barf",
    "barface",
    "barfface",
    "bastard",
    "bastardo",
    "bastards",
    "bastinado",
    "batty boy",
    "bawdy",
    "bazongas",
    "bazooms",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beardedclam",
    "beastial",
    "beastiality",
    "beatch",
    "beater",
    "beatyourmeat",
    "beaver",
    "beaver cleaver",
    "beaver lips",
    "beef curtain",
    "beef curtains",
    "beer",
    "beeyotch",
    "bellend",
    "bender",
    "beotch",
    "bestial",
    "bestiality",
    "bi+ch",
    "bi-sexual",
    "biatch",
    "bicurious",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bigbastard",
    "bigbutt",
    "bigger",
    "bigtits",
    "bimbo",
    "bimbos",
    "bint",
    "birdlock",
    "bisexual",
    "bitch",
    "bitch tit",
    "bitchass",
    "bitched",
    "bitcher",
    "bitchers",
    "bitches",
    "bitchez",
    "bitchin",
    "bitching",
    "bitchtits",
    "bitchy",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "bloodclaat",
    "bloody",
    "bloody hell",
    "blow",
    "blow job",
    "blow me",
    "blow mud",
    "blow your load",
    "blowjob",
    "blowjobs",
    "blue waffle",
    "blumpkin",
    "boang",
    "bod",
    "bodily",
    "bogan",
    "bohunk",
    "boink",
    "boiolas",
    "bollick",
    "bollock",
    "bollocks",
    "bollok",
    "bollox",
    "bomd",
    "bondage",
    "bone",
    "boned",
    "boner",
    "boners",
    "bong",
    "boob",
    "boobies",
    "boobs",
    "booby",
    "booger",
    "bookie",
    "boong",
    "boonga",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "bootee",
    "bootie",
    "booty",
    "booty call",
    "booze",
    "boozer",
    "boozy",
    "bosom",
    "bosomy",
    "bowel",
    "bowels",
    "bra",
    "brassiere",
    "breast",
    "breastjob",
    "breastlover",
    "breastman",
    "breasts",
    "breeder",
    "brotherfucker",
    "brown showers",
    "brunette action",
    "buceta",
    "bugger",
    "buggered",
    "buggery",
    "bukkake",
    "bull shit",
    "bullcrap",
    "bulldike",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bullshits",
    "bullshitted",
    "bullturds",
    "bum",
    "bum boy",
    "bumblefuck",
    "bumclat",
    "bumfuck",
    "bummer",
    "bung",
    "bung hole",
    "bunga",
    "bunghole",
    "bunny fucker",
    "bust a load",
    "busty",
    "butchdike",
    "butchdyke",
    "butt",
    "butt fuck",
    "butt plug",
    "butt-bang",
    "butt-fuck",
    "butt-fucker",
    "butt-pirate",
    "buttbang",
    "buttcheeks",
    "buttface",
    "buttfuck",
    "buttfucka",
    "buttfucker",
    "butthead",
    "butthole",
    "buttman",
    "buttmuch",
    "buttmunch",
    "buttmuncher",
    "buttplug",
    "c-0-c-k",
    "c-o-c-k",
    "c-u-n-t",
    "c.0.c.k",
    "c.o.c.k.",
    "c.u.n.t",
    "c0ck",
    "c0cksucker",
    "caca",
    "cahone",
    "camel toe",
    "cameltoe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "cawk",
    "cervix",
    "chesticle",
    "chi-chi man",
    "chick with a dick",
    "child-fucker",
    "chin",
    "chinc",
    "chincs",
    "chink",
    "chinky",
    "choad",
    "choade",
    "choc ice",
    "chocolate rosebuds",
    "chode",
    "chodes",
    "chota bags",
    "cipa",
    "circlejerk",
    "cl1t",
    "cleveland steamer",
    "climax",
    "clit",
    "clit licker",
    "clitface",
    "clitfuck",
    "clitoris",
    "clitorus",
    "clits",
    "clitty",
    "clitty litter",
    "clogwog",
    "clover clamps",
    "clunge",
    "clusterfuck",
    "cnut",
    "cocain",
    "cocaine",
    "cock",
    "cock pocket",
    "cock snot",
    "cock sucker",
    "cock-sucker",
    "cockass",
    "cockbite",
    "cockblock",
    "cockburger",
    "cockeye",
    "cockface",
    "cockfucker",
    "cockhead",
    "cockholster",
    "cockjockey",
    "cockknocker",
    "cockknoker",
    "cocklicker",
    "cocklover",
    "cocklump",
    "cockmaster",
    "cockmongler",
    "cockmongruel",
    "cockmonkey",
    "cockmunch",
    "cockmuncher",
    "cocknose",
    "cocknugget",
    "cocks",
    "cockshit",
    "cocksmith",
    "cocksmoke",
    "cocksmoker",
    "cocksniffer",
    "cocksucer",
    "cocksuck",
    "cocksucked",
    "cocksucker",
    "cocksuckers",
    "cocksucking",
    "cocksucks",
    "cocksuka",
    "cocksukka",
    "cockwaffle",
    "coffin dodger",
    "coital",
    "cok",
    "cokmuncher",
    "coksucka",
    "commie",
    "condom",
    "coochie",
    "coochy",
    "coon",
    "coonnass",
    "coons",
    "cooter",
    "cop some wood",
    "coprolagnia",
    "coprophilia",
    "corksucker",
    "cornhole",
    "corp whore",
    "cox",
    "crabs",
    "crack",
    "crack-whore",
    "cracker",
    "crackwhore",
    "crap",
    "crappy",
    "creampie",
    "cretin",
    "crikey",
    "cripple",
    "crotte",
    "cum",
    "cum chugger",
    "cum dumpster",
    "cum freak",
    "cum guzzler",
    "cumbubble",
    "cumdump",
    "cumdumpster",
    "cumguzzler",
    "cumjockey",
    "cummer",
    "cummin",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cumstain",
    "cumtart",
    "cunilingus",
    "cunillingus",
    "cunn",
    "cunnie",
    "cunnilingus",
    "cunntt",
    "cunny",
    "cunt",
    "cunt hair",
    "cunt-struck",
    "cuntass",
    "cuntbag",
    "cuntface",
    "cuntfuck",
    "cuntfucker",
    "cunthole",
    "cunthunter",
    "cuntlick",
    "cuntlicker",
    "cuntlicking",
    "cuntrag",
    "cunts",
    "cuntsicle",
    "cuntslut",
    "cuntsucker",
    "cut rope",
    "cyalis",
    "cyberfuc",
    "cyberfuck",
    "cyberfucked",
    "cyberfucker",
    "cyberfuckers",
    "cyberfucking",
    "cybersex",
    "d0ng",
    "d0uch3",
    "d0uche",
    "d1ck",
    "d1ld0",
    "d1ldo",
    "dago",
    "dagos",
    "dammit",
    "damn",
    "damned",
    "damnit",
    "darkie",
    "darn",
    "date rape",
    "daterape",
    "dawgie-style",
    "deep throat",
    "deepthroat",
    "deggo",
    "dendrophilia",
    "dick",
    "dick head",
    "dick hole",
    "dick shy",
    "dick-ish",
    "dick-sneeze",
    "dickbag",
    "dickbeaters",
    "dickbrain",
    "dickdipper",
    "dickface",
    "dickflipper",
    "dickfuck",
    "dickfucker",
    "dickhead",
    "dickheads",
    "dickhole",
    "dickish",
    "dickjuice",
    "dickmilk",
    "dickmonger",
    "dickripper",
    "dicks",
    "dicksipper",
    "dickslap",
    "dicksucker",
    "dicksucking",
    "dicktickler",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dickwhipper",
    "dickwod",
    "dickzipper",
    "diddle",
    "dike",
    "dildo",
    "dildos",
    "diligaf",
    "dillweed",
    "dimwit",
    "dingle",
    "dingleberries",
    "dingleberry",
    "dink",
    "dinks",
    "dipship",
    "dipshit",
    "dirsa",
    "dirty",
    "dirty pillows",
    "dirty sanchez",
    "dlck",
    "dog style",
    "dog-fucker",
    "doggie style",
    "doggie-style",
    "doggiestyle",
    "doggin",
    "dogging",
    "doggy style",
    "doggy-style",
    "doggystyle",
    "dolcett",
    "domination",
    "dominatrix",
    "dommes",
    "dong",
    "donkey punch",
    "donkeypunch",
    "donkeyribber",
    "doochbag",
    "doofus",
    "dookie",
    "doosh",
    "dopey",
    "double dong",
    "double penetration",
    "doublelift",
    "douch3",
    "douche",
    "douche-fag",
    "douchebag",
    "douchebags",
    "douchewaffle",
    "douchey",
    "dp action",
    "drunk",
    "dry hump",
    "duche",
    "dumass",
    "dumb ass",
    "dumbass",
    "dumbasses",
    "dumbcunt",
    "dumbfuck",
    "dumbshit",
    "dummy",
    "dumshit",
    "dvda",
    "dyke",
    "dykes",
    "eat a dick",
    "eat hair pie",
    "eat my ass",
    "eatpussy",
    "ecchi",
    "ejaculate",
    "ejaculated",
    "ejaculates",
    "ejaculating",
    "ejaculatings",
    "ejaculation",
    "ejakulate",
    "enlargement",
    "erect",
    "erection",
    "erotic",
    "erotism",
    "escort",
    "essohbee",
    "eunuch",
    "extacy",
    "extasy",
    "f u c k",
    "f u c k e r",
    "f-u-c-k",
    "f.u.c.k",
    "f4nny",
    "f_u_c_k",
    "facefucker",
    "facial",
    "fack",
    "fag",
    "fagbag",
    "fagfucker",
    "fagg",
    "fagged",
    "fagging",
    "faggit",
    "faggitt",
    "faggot",
    "faggotcock",
    "faggots",
    "faggs",
    "fagot",
    "fagots",
    "fags",
    "fagtard",
    "faig",
    "faigt",
    "fanny",
    "fannybandit",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fart",
    "fartknocker",
    "fastfuck",
    "fat",
    "fatass",
    "fatfuck",
    "fatfucker",
    "fcuk",
    "fcuker",
    "fcuking",
    "fecal",
    "feck",
    "fecker",
    "felch",
    "felcher",
    "felching",
    "fellate",
    "fellatio",
    "feltch",
    "feltcher",
    "female squirting",
    "femdom",
    "fenian",
    "figging",
    "fingerbang",
    "fingerfuck",
    "fingerfucked",
    "fingerfucker",
    "fingerfuckers",
    "fingerfucking",
    "fingerfucks",
    "fingering",
    "fist fuck",
    "fisted",
    "fistfuck",
    "fistfucked",
    "fistfucker",
    "fistfuckers",
    "fistfucking",
    "fistfuckings",
    "fistfucks",
    "fisting",
    "fisty",
    "flamer",
    "flange",
    "flaps",
    "fleshflute",
    "flog the log",
    "floozy",
    "foad",
    "foah",
    "fondle",
    "foobar",
    "fook",
    "fooker",
    "foot fetish",
    "footfuck",
    "footfucker",
    "footjob",
    "footlicker",
    "foreskin",
    "freakfuck",
    "freakyfucker",
    "freefuck",
    "freex",
    "frigg",
    "frigga",
    "frotting",
    "fubar",
    "fuc",
    "fuck",
    "fuck buttons",
    "fuck hole",
    "fuck off",
    "fuck puppet",
    "fuck trophy",
    "fuck yo mama",
    "fuck you",
    "fuck-ass",
    "fuck-bitch",
    "fuck-tard",
    "fucka",
    "fuckass",
    "fuckbag",
    "fuckboy",
    "fuckbrain",
    "fuckbutt",
    "fuckbutter",
    "fucked",
    "fuckedup",
    "fucker",
    "fuckers",
    "fuckersucker",
    "fuckface",
    "fuckfreak",
    "fuckhead",
    "fuckheads",
    "fuckher",
    "fuckhole",
    "fuckin",
    "fucking",
    "fuckingbitch",
    "fuckings",
    "fuckingshitmotherfucker",
    "fuckme",
    "fuckmeat",
    "fuckmehard",
    "fuckmonkey",
    "fucknugget",
    "fucknut",
    "fucknutt",
    "fuckoff",
    "fucks",
    "fuckstick",
    "fucktard",
    "fucktards",
    "fucktart",
    "fucktoy",
    "fucktwat",
    "fuckup",
    "fuckwad",
    "fuckwhit",
    "fuckwhore",
    "fuckwit",
    "fuckwitt",
    "fuckyou",
    "fudge packer",
    "fudge-packer",
    "fudgepacker",
    "fuk",
    "fuker",
    "fukker",
    "fukkers",
    "fukkin",
    "fuks",
    "fukwhit",
    "fukwit",
    "fuq",
    "futanari",
    "fux",
    "fux0r",
    "fvck",
    "fxck",
    "g-spot",
    "gae",
    "gai",
    "gang bang",
    "gang-bang",
    "gangbang",
    "gangbanged",
    "gangbangs",
    "ganja",
    "gash",
    "gassy ass",
    "gay sex",
    "gayass",
    "gaybob",
    "gaydo",
    "gayfuck",
    "gayfuckist",
    "gaylord",
    "gays",
    "gaysex",
    "gaytard",
    "gaywad",
    "gender bender",
    "genitals",
    "gey",
    "gfy",
    "ghay",
    "ghey",
    "giant cock",
    "gigolo",
    "ginger",
    "gippo",
    "girl on",
    "girl on top",
    "girls gone wild",
    "git",
    "glans",
    "goatcx",
    "goatse",
    "god damn",
    "god-dam",
    "god-damned",
    "godamn",
    "godamnit",
    "goddam",
    "goddammit",
    "goddamn",
    "goddamned",
    "goddamnit",
    "goddamnmuthafucker",
    "godsdamn",
    "gokkun",
    "golden shower",
    "goldenshower",
    "golliwog",
    "gonad",
    "gonads",
    "gonorrehea",
    "goo girl",
    "gooch",
    "goodpoop",
    "gook",
    "gooks",
    "goregasm",
    "gotohell",
    "gringo",
    "grope",
    "group sex",
    "gspot",
    "gtfo",
    "guido",
    "guro",
    "h0m0",
    "h0mo",
    "ham flap",
    "hand job",
    "handjob",
    "hard core",
    "hard on",
    "hardcore",
    "hardcoresex",
    "he-she",
    "he11",
    "headfuck",
    "hebe",
    "heeb",
    "hell",
    "hemp",
    "hentai",
    "heroin",
    "herp",
    "herpes",
    "herpy",
    "heshe",
    "hitler",
    "hiv",
    "ho",
    "hoar",
    "hoare",
    "hobag",
    "hoe",
    "hoer",
    "holy shit",
    "hom0",
    "homey",
    "homo",
    "homodumbshit",
    "homoerotic",
    "homoey",
    "honkey",
    "honky",
    "hooch",
    "hookah",
    "hooker",
    "hoor",
    "hootch",
    "hooter",
    "hooters",
    "hore",
    "horniest",
    "horny",
    "hot carl",
    "hot chick",
    "hotpussy",
    "hotsex",
    "how to kill",
    "how to murdep",
    "how to murder",
    "huge fat",
    "hump",
    "humped",
    "humping",
    "hun",
    "hussy",
    "hymen",
    "iap",
    "iberian slap",
    "inbred",
    "incest",
    "injun",
    "intercourse",
    "j3rk0ff",
    "jack off",
    "jack-off",
    "jackass",
    "jackasses",
    "jackhole",
    "jackoff",
    "jaggi",
    "jagoff",
    "jail bait",
    "jailbait",
    "jap",
    "japs",
    "jelly donut",
    "jerk",
    "jerk off",
    "jerk-off",
    "jerk0ff",
    "jerkass",
    "jerked",
    "jerkoff",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jism",
    "jiz",
    "jizm",
    "jizz",
    "jizzed",
    "jock",
    "juggs",
    "jungle bunny",
    "junglebunny",
    "junkie",
    "junky",
    "kafir",
    "kawk",
    "kike",
    "kikes",
    "kill",
    "kinbaku",
    "kinkster",
    "kinky",
    "kkk",
    "klan",
    "knob",
    "knob end",
    "knobbing",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "kock",
    "kondum",
    "kondums",
    "kooch",
    "kooches",
    "kootch",
    "kraut",
    "kum",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "kunja",
    "kunt",
    "kwif",
    "kyke",
    "l3i+ch",
    "l3itch",
    "labia",
    "lameass",
    "lardass",
    "leather restraint",
    "leather straight jacket",
    "lech",
    "lemon party",
    "leper",
    "lesbian",
    "lesbians",
    "lesbo",
    "lesbos",
    "lez",
    "lezbian",
    "lezbians",
    "lezbo",
    "lezbos",
    "lezza",
    "lezzie",
    "lezzies",
    "lezzy",
    "lmao",
    "lmfao",
    "loin",
    "loins",
    "lolita",
    "looney",
    "lovemaking",
    "lube",
    "lust",
    "lusting",
    "lusty",
    "m-fucking",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "mafugly",
    "make me come",
    "male squirting",
    "mams",
    "masochist",
    "massa",
    "master-bate",
    "masterb8",
    "masterbat",
    "masterbat3",
    "masterbate",
    "masterbating",
    "masterbation",
    "masterbations",
    "masturbate",
    "masturbating",
    "masturbation",
    "maxi",
    "mcfagget",
    "menage a trois",
    "menses",
    "menstruate",
    "menstruation",
    "meth",
    "mick",
    "middle finger",
    "midget",
    "milf",
    "minge",
    "minger",
    "missionary position",
    "mo-fo",
    "mof0",
    "mofo",
    "molest",
    "mong",
    "moo moo foo foo",
    "moolie",
    "moron",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckaz",
    "mothafucked",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafucks",
    "mother fucker",
    "motherfuck",
    "motherfucka",
    "motherfucked",
    "motherfucker",
    "motherfuckers",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckka",
    "motherfucks",
    "mound of venus",
    "mr hands",
    "mtherfucker",
    "mthrfucker",
    "mthrfucking",
    "muff",
    "muff diver",
    "muff puff",
    "muffdiver",
    "muffdiving",
    "munging",
    "munter",
    "murder",
    "mutha",
    "muthafecker",
    "muthafuckaz",
    "muthafuckker",
    "muther",
    "mutherfucker",
    "mutherfucking",
    "muthrfucking",
    "n1gga",
    "n1gger",
    "nad",
    "nads",
    "naked",
    "nambla",
    "napalm",
    "nappy",
    "nawashi",
    "nazi",
    "nazism",
    "need the dick",
    "negro",
    "neonazi",
    "nig nog",
    "nig-nog",
    "nigaboo",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggas",
    "niggaz",
    "nigger",
    "niggers",
    "niggle",
    "niglet",
    "nimphomania",
    "nimrod",
    "ninny",
    "nipple",
    "nipples",
    "nob",
    "nob jokey",
    "nobhead",
    "nobjocky",
    "nobjokey",
    "nonce",
    "nooky",
    "nsfw images",
    "nude",
    "nudity",
    "numbnuts",
    "nut butter",
    "nut sack",
    "nutsack",
    "nutter",
    "nympho",
    "nymphomania",
    "octopussy",
    "old bag",
    "omg",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "opiate",
    "opium",
    "oral",
    "orally",
    "organ",
    "orgasim",
    "orgasims",
    "orgasm",
    "orgasmic",
    "orgasms",
    "orgies",
    "orgy",
    "ovary",
    "ovum",
    "ovums",
    "p.u.s.s.y.",
    "p0rn",
    "paddy",
    "paedophile",
    "paki",
    "panooch",
    "pansy",
    "pantie",
    "panties",
    "panty",
    "pastie",
    "pasty",
    "pawn",
    "pcp",
    "pecker",
    "peckerhead",
    "pedo",
    "pedobear",
    "pedophile",
    "pedophilia",
    "pedophiliac",
    "pee",
    "peepee",
    "pegging",
    "penetrate",
    "penetration",
    "penial",
    "penile",
    "penis",
    "penisbanger",
    "penisfucker",
    "penispuffer",
    "perversion",
    "peyote",
    "phalli",
    "phallic",
    "phone sex",
    "phonesex",
    "phuck",
    "phuk",
    "phuked",
    "phuking",
    "phukked",
    "phukking",
    "phuks",
    "phuq",
    "piece of shit",
    "pigfucker",
    "pikey",
    "pillowbiter",
    "pimp",
    "pimpis",
    "pinko",
    "piss",
    "piss off",
    "piss pig",
    "piss-off",
    "pissed",
    "pissed off",
    "pisser",
    "pissers",
    "pisses",
    "pissflaps",
    "pissin",
    "pissing",
    "pissoff",
    "pisspig",
    "playboy",
    "pleasure chest",
    "pms",
    "polack",
    "pole smoker",
    "polesmoker",
    "pollock",
    "ponyplay",
    "poof",
    "poon",
    "poonani",
    "poonany",
    "poontang",
    "poop",
    "poop chute",
    "poopchute",
    "poopuncher",
    "porch monkey",
    "porchmonkey",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "pot",
    "potty",
    "prick",
    "pricks",
    "prickteaser",
    "prig",
    "prince albert piercing",
    "prod",
    "pron",
    "prostitute",
    "prude",
    "psycho",
    "pthc",
    "pube",
    "pubes",
    "pubic",
    "pubis",
    "punani",
    "punanny",
    "punany",
    "punkass",
    "punky",
    "punta",
    "puss",
    "pusse",
    "pussi",
    "pussies",
    "pussy",
    "pussy fart",
    "pussy palace",
    "pussylicking",
    "pussypounder",
    "pussys",
    "pust",
    "puto",
    "queaf",
    "queef",
    "queer",
    "queerbait",
    "queerhole",
    "queero",
    "queers",
    "quicky",
    "quim",
    "r-tard",
    "racy",
    "raghead",
    "raging boner",
    "rape",
    "raped",
    "raper",
    "rapey",
    "raping",
    "rapist",
    "raunch",
    "rectal",
    "rectum",
    "rectus",
    "reefer",
    "reetard",
    "reich",
    "renob",
    "retard",
    "retarded",
    "reverse cowgirl",
    "revue",
    "rimjaw",
    "rimjob",
    "rimming",
    "ritard",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "rtard",
    "rubbish",
    "rum",
    "rump",
    "rumprammer",
    "ruski",
    "rusty trombone",
    "s hit",
    "s&m",
    "s-h-1-t",
    "s-h-i-t",
    "s-o-b",
    "s.h.i.t.",
    "s.o.b.",
    "s0b",
    "s_h_i_t",
    "sadism",
    "sadist",
    "sambo",
    "sand nigger",
    "sandbar",
    "sandler",
    "sandnigger",
    "sanger",
    "santorum",
    "sausage queen",
    "scag",
    "scantily",
    "scat",
    "schizo",
    "schlong",
    "scissoring",
    "screw",
    "screwed",
    "screwing",
    "scroat",
    "scrog",
    "scrot",
    "scrote",
    "scrotum",
    "scrud",
    "scum",
    "seaman",
    "seamen",
    "seduce",
    "seks",
    "semen",
    "sex",
    "sexo",
    "sexual",
    "sexy",
    "sh!+",
    "sh!t",
    "sh1t",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "shamedame",
    "shaved beaver",
    "shaved pussy",
    "shemale",
    "shi+",
    "shibari",
    "shirt lifter",
    "shit",
    "shit ass",
    "shit fucker",
    "shitass",
    "shitbag",
    "shitbagger",
    "shitblimp",
    "shitbrains",
    "shitbreath",
    "shitcanned",
    "shitcunt",
    "shitdick",
    "shite",
    "shiteater",
    "shited",
    "shitey",
    "shitface",
    "shitfaced",
    "shitfuck",
    "shitfull",
    "shithead",
    "shitheads",
    "shithole",
    "shithouse",
    "shiting",
    "shitings",
    "shits",
    "shitspitter",
    "shitstain",
    "shitt",
    "shitted",
    "shitter",
    "shitters",
    "shittier",
    "shittiest",
    "shitting",
    "shittings",
    "shitty",
    "shiz",
    "shiznit",
    "shota",
    "shrimping",
    "sissy",
    "skag",
    "skank",
    "skeet",
    "skullfuck",
    "slag",
    "slanteye",
    "slave",
    "sleaze",
    "sleazy",
    "slope",
    "slut",
    "slut bucket",
    "slutbag",
    "slutdumper",
    "slutkiss",
    "sluts",
    "smartass",
    "smartasses",
    "smeg",
    "smegma",
    "smut",
    "smutty",
    "snatch",
    "sniper",
    "snowballing",
    "snuff",
    "sod off",
    "sodom",
    "sodomize",
    "sodomy",
    "son of a bitch",
    "son of a motherless goat",
    "son of a whore",
    "son-of-a-bitch",
    "souse",
    "soused",
    "spac",
    "spade",
    "sperm",
    "spic",
    "spick",
    "spik",
    "spiks",
    "splooge",
    "splooge moose",
    "spooge",
    "spook",
    "spread legs",
    "spunk",
    "steamy",
    "stfu",
    "stiffy",
    "stoned",
    "strap on",
    "strapon",
    "strappado",
    "strip",
    "strip club",
    "stroke",
    "stupid",
    "style doggy",
    "suck",
    "suckass",
    "sucked",
    "sucking",
    "sucks",
    "suicide girls",
    "sultry women",
    "sumofabiatch",
    "swastika",
    "swinger",
    "t1t",
    "t1tt1e5",
    "t1tties",
    "taff",
    "taig",
    "tainted love",
    "taking the piss",
    "tampon",
    "tard",
    "tart",
    "taste my",
    "tawdry",
    "tea bagging",
    "teabagging",
    "teat",
    "teets",
    "teez",
    "terd",
    "teste",
    "testee",
    "testes",
    "testical",
    "testicle",
    "testis",
    "threesome",
    "throating",
    "thrust",
    "thug",
    "thundercunt",
    "tied up",
    "tight white",
    "tinkle",
    "tit",
    "tit wank",
    "titfuck",
    "titi",
    "tities",
    "tits",
    "titt",
    "tittie5",
    "tittiefucker",
    "titties",
    "titty",
    "tittyfuck",
    "tittyfucker",
    "tittywank",
    "titwank",
    "toke",
    "tongue in a",
    "toots",
    "topless",
    "tosser",
    "towelhead",
    "tramp",
    "tranny",
    "transsexual",
    "trashy",
    "tribadism",
    "trumped",
    "tub girl",
    "tubgirl",
    "turd",
    "tush",
    "tushy",
    "tw4t",
    "twat",
    "twathead",
    "twatlips",
    "twats",
    "twatty",
    "twatwaffle",
    "twink",
    "twinkie",
    "two fingers",
    "two fingers with tongue",
    "two girls one cup",
    "twunt",
    "twunter",
    "ugly",
    "unclefucker",
    "undies",
    "undressing",
    "unwed",
    "upskirt",
    "urethra play",
    "urinal",
    "urine",
    "urophilia",
    "uterus",
    "uzi",
    "v14gra",
    "v1gra",
    "va-j-j",
    "vag",
    "vagina",
    "vajayjay",
    "valium",
    "venus mound",
    "veqtable",
    "viagra",
    "vibrator",
    "violet wand",
    "virgin",
    "vixen",
    "vjayjay",
    "vodka",
    "vomit",
    "vorarephilia",
    "voyeur",
    "vulgar",
    "vulva",
    "w00se",
    "wad",
    "wang",
    "wank",
    "wanker",
    "wankjob",
    "wanky",
    "wazoo",
    "wedgie",
    "weed",
    "weenie",
    "weewee",
    "weiner",
    "weirdo",
    "wench",
    "wet dream",
    "wetback",
    "wh0re",
    "wh0reface",
    "white power",
    "whitey",
    "whiz",
    "whoar",
    "whoralicious",
    "whore",
    "whorealicious",
    "whorebag",
    "whored",
    "whoreface",
    "whorehopper",
    "whorehouse",
    "whores",
    "whoring",
    "wigger",
    "willies",
    "willy",
    "window licker",
    "wiseass",
    "wiseasses",
    "wog",
    "womb",
    "woody",
    "wop",
    "wrapping men",
    "wrinkled starfish",
    "wtf",
    "x-rated",
    "xrated",
    "xx",
    "xxx",
    "yaoi",
    "yeasty",
    "yellow showers",
    "yid",
    "yiffy",
    "yobbo",
    "zoophile",
    "zoophilia",
    "zoophilia2 girls 1 cup",
    "zubb"
)
val badFrench = arrayOf(
    " enculé",
    " idiot",
    " idiote",
    " merde",
    " toi",
    " va t’en",
    "Je m’en bats les couilles",
    "abruti",
    "aller se faire foutre",
    "allez",
    "amène ta mère pourque je te refasse",
    "avale mes couilles",
    "bachie coupe",
    "baise",
    "baise moi mor",
    "baise toi",
    "baiser",
    "bander",
    "batard",
    "bigornette",
    "bique",
    "bise",
    "bite",
    "bitte",
    "bloblos",
    "bon sang",
    "bordel",
    "bordel de merde",
    "bosser",
    "bourré",
    "bourrée",
    "brackmard",
    "branlage",
    "branler",
    "branlette",
    "branleur",
    "branleur de chiens morts",
    "branleuse",
    "brouter le cresson",
    "broutte-minou",
    "brûle en enfer",
    "brûle en l'enfer",
    "c'est des conneries",
    "caca",
    "cailler",
    "calice",
    "calisse",
    "casse-couille",
    "casse-couilles",
    "casse-toi",
    "casser les couilles",
    "cave",
    "ce putain d’embouteillage",
    "ce putain d’ordinateur",
    "cela me soûle",
    "charogne",
    "chatte",
    "chiant",
    "chiante",
    "chiasse",
    "chien sale",
    "chienne",
    "chier",
    "chieur",
    "chieuse",
    "chiottes",
    "choleque de merde",
    "clito",
    "clitoris",
    "con",
    "conasse",
    "connard",
    "connasse",
    "conne",
    "connerie",
    "conneries",
    "couille",
    "couilles",
    "couillon",
    "couillonne",
    "cramouille",
    "criss",
    "crisse",
    "crosseur",
    "crève la gueule ouverte",
    "crétin",
    "cul",
    "c’est chiant",
    "c’est des conneries",
    "c’est le bordel ici",
    "c’est naze",
    "c’est quoi ce bordel",
    "c’est vraiment de ta faute",
    "debile",
    "dinde",
    "drague",
    "déconne",
    "déconner",
    "dégage",
    "dégueulasse",
    "dégénéré",
    "emmerdant",
    "emmerder",
    "emmerdeur",
    "emmerdeuse",
    "enculer",
    "enculer les mouches",
    "enculer une mouche",
    "enculeur",
    "enculeurs",
    "enculé",
    "enculé de ta mère",
    "enculé toi salaud",
    "enculée",
    "enfoiré",
    "enfoirée",
    "face de cul",
    "faire enculer",
    "faire foutre",
    "fais chier",
    "fait moi jouir",
    "ferme ta gueule",
    "fiche moi le paix",
    "fif",
    "fille de pute",
    "film de cul",
    "fils de pute",
    "fils de salope",
    "folle",
    "fous le camps",
    "fous le camps et morte",
    "foutre",
    "foutre la merde",
    "foutre le bordel",
    "framble",
    "fucker",
    "garage à bite",
    "garce",
    "gerbe",
    "gerber",
    "gouine",
    "graine",
    "grande folle",
    "grogniasse",
    "gros tas",
    "gross cul",
    "guenon",
    "gueule",
    "idiot",
    "idiote",
    "il est stupide",
    "il fait chaud ici",
    "il me fait chier",
    "imbécile",
    "j'en ai marre",
    "j'en ai plus rien à foutre",
    "j'en ai ral le bol",
    "j'en ai ral le cul",
    "j'en ai rien à cirer",
    "j'en ai rien à foutre",
    "je m'en fiche",
    "je m'en fou",
    "je m'en fous",
    "je m'en sacre",
    "je me fais chier",
    "je me fais chier ici",
    "je m’emmerde",
    "je m’en fiche",
    "je m’en fou",
    "je m’en fous",
    "je pis dans ta bouche",
    "je t'emmerde",
    "je t'encule",
    "je te déteste",
    "je te nique ta race sale fils de chien",
    "je veux faire l’amour avec toi",
    "jouir",
    "j’ai baisé ta mère",
    "j’ai envie de chier",
    "j’en ai marre",
    "j’en ai plus rien à foutre",
    "j’en ai ral le bol",
    "j’en ai ral le cul",
    "j’en ai ras le bol",
    "j’en ai rien à cirer",
    "la chatte",
    "la meme chose a toi",
    "la putain de ta mère",
    "la vache",
    "laisse-moi tranquille",
    "le con",
    "lèche-cul",
    "ma couille",
    "mal baisée",
    "mance",
    "mange de la merde",
    "mange ma bite",
    "mange merde et morte",
    "mange tes grands morts",
    "maudit",
    "merdasse",
    "merde",
    "merde embulante",
    "merdeuse",
    "merdeux",
    "mes couilles en toi",
    "metteux",
    "meuf",
    "mince",
    "mon dieu",
    "morceau de merde",
    "ménage à trois",
    "nana",
    "ne rien foutre",
    "negro",
    "nique la police",
    "nique ta mere",
    "nique ta mère",
    "nique ta mère espèce de gros bâtard de merde",
    "nique ta mère la chauve",
    "nique ta race",
    "niquer",
    "nom de dieu",
    "nom de dieu de merde",
    "noune",
    "nègre",
    "oh",
    "oh la vache",
    "oh putain de merde",
    "ordure",
    "osti",
    "osti de calisse de tabarnak",
    "ostie",
    "palucher",
    "partir en couille",
    "pauvre con",
    "petit tabernac",
    "petite pute",
    "pipi",
    "pisser",
    "pisser dans",
    "plotte",
    "pouffe",
    "pouffiasse",
    "poupée",
    "pousse-crotte",
    "punaise",
    "purée",
    "putain",
    "putain de bordel de merde",
    "putain de merde",
    "putain de temps",
    "putain t’es moche",
    "pute",
    "pédale",
    "pédé",
    "pétasse",
    "péter",
    "péter la cenne",
    "péter les couilles",
    "quel bordel",
    "quel salaud",
    "queue",
    "queutard",
    "qu’est-ce que tu branles",
    "ramoner",
    "retourne enculer",
    "rien à branler",
    "rien à foutre",
    "sa mère",
    "sa mère la pute",
    "sa race",
    "sac merde",
    "sac vin",
    "sac à foutre",
    "sac à merde",
    "sacrament",
    "sacrebleu",
    "salaud",
    "salopard",
    "salope",
    "saloperie",
    "se foutre dans la merde",
    "se taire",
    "stupide",
    "suce",
    "suceuse",
    "s’en branler",
    "s’en foutre",
    "t'as pas de couilles",
    "t'es rien qu'un petit connard",
    "t'es un salaud",
    "ta gueule",
    "ta mere est francaise",
    "ta mere suce des bites en enfer",
    "ta mère elle suce des ours",
    "ta mère est une pute",
    "ta mère la pute",
    "tabarnak",
    "tais-toi",
    "tanche",
    "tantouze",
    "tapette",
    "tarte",
    "tas de marde",
    "tata",
    "teuch",
    "teuf",
    "traînée",
    "tringler",
    "trique",
    "troncher",
    "trou de cul",
    "trou du cul",
    "très stupide",
    "tu commence m’enmerder",
    "tu es con",
    "tu es très stupide",
    "tu es un putain",
    "tu et un ane",
    "tu fais chier",
    "tu m'emmerdes",
    "tu me fais chier",
    "tu me fatigues",
    "tu me gonfles",
    "turlute",
    "téteux",
    "tête de nœud",
    "tête moi le dard",
    "tête moi le noeud",
    "t’as intérêt ne pas m’énervé",
    "t’as pas de couilles",
    "t’es débile",
    "t’es rien qu’un petit connard",
    "t’es un salaud",
    "t’es vraiment emmerdant",
    "une salope",
    "va te branler",
    "va te crosser",
    "va te faire",
    "va te faire baiser",
    "va te faire enculer",
    "va te faire foutre",
    "va te faire mettre",
    "va te faire voir",
    "va te tripoter",
    "vache",
    "vas faire foutre a la vache",
    "veuve",
    "vous sentez comme le boeuf et le fromage",
    "vous vissez",
    "vous êtes stupide",
    "zigounette",
    "zizi",
    "zut",
    "zut alors",
    "ça casse les couilles",
    "ça craint",
    "ça fait shier",
    "ça m'emmerde",
    "ça me casse les couilles",
    "ça me fait chier",
    "ça me saoûle",
    "ça pue",
    "ça schlingue",
    "étron",
)
val badGerman = arrayOf(
    "abschaum",
    "affenschwanz",
    "ah du schwein",
    "alter muschi",
    "alter wichser",
    "am blitz geleckt haben",
    "analritter",
    "arsch",
    "arschficker",
    "arschfotze",
    "arschgeige",
    "arschgesicht",
    "arschkeks",
    "arschkriecher",
    "arschlecker",
    "arschloch",
    "auberfeiger",
    "aufgeilen",
    "backpfeifengesicht",
    "bastard",
    "bimbo",
    "bloede kuh",
    "blutige sau",
    "blvde fotze",
    "blöde gans",
    "blöde stinkpot",
    "blödmann",
    "blödsinn",
    "bonze",
    "bratze",
    "bruchbude",
    "bumsen",
    "das arschloch",
    "das ist mir scheißegal",
    "das miststück",
    "das schwein",
    "depp",
    "der dreckskerl",
    "der fotzenlecker",
    "der mist",
    "der mistkerl",
    "der wichser",
    "die drecksau",
    "die sau",
    "die verarsche",
    "donnerwetter",
    "dreckige hure",
    "drecksack",
    "drecksau",
    "dreckskerl",
    "drecksnest",
    "du Hurensohn",
    "du bastard",
    "du blöde kuh",
    "du fickfehler",
    "du hurensohn",
    "du kannst mich mal",
    "du sau",
    "du schwein",
    "du weichei",
    "dummbatz",
    "dumme",
    "dumme kuh",
    "dumme nuss",
    "dummkopf",
    "dumpfbacke",
    "dödel",
    "erarschen",
    "fahr zur holle",
    "feigling",
    "fick",
    "fick deine mutter",
    "fick dich",
    "fick dich arschloch",
    "fick dich in knie",
    "ficke",
    "ficken",
    "ficker",
    "filzlaus",
    "flachwichser",
    "flittchen",
    "fotze",
    "fratze",
    "geh zum teufel",
    "gottverdammt",
    "hackfresse",
    "halt deinen mund",
    "halt die fotze",
    "halt die klappe",
    "hat jemand dir ins gehirn geschissen",
    "hirnrissig",
    "homo",
    "hosenscheisser",
    "huhrensohn",
    "hure",
    "huren",
    "huren sohn",
    "hurensohn",
    "ich ficke deine mutter",
    "ich ficke deine schwester",
    "ich hasse dich",
    "ich will dich ficken",
    "ich will ficken",
    "idiot",
    "ische",
    "kackbratze",
    "kacke",
    "kacken",
    "kackwurst",
    "kampflesbe",
    "kanake",
    "kimme",
    "klugscheißer",
    "küss meinen arsch",
    "lech mien arsch",
    "leck mich",
    "leck mich am arsch",
    "lesbe",
    "lick",
    "lms",
    "lusche",
    "lutsch mein’ schwanz",
    "lutschen",
    "lutsch’ meine eier",
    "lümmel",
    "milf",
    "mist",
    "miststück",
    "morgenlatte",
    "mufti",
    "muschi",
    "muschi lecker",
    "mutterficker",
    "möpse",
    "möse",
    "nackt",
    "neger",
    "nigger",
    "nippel",
    "nutte",
    "ohne scheiß",
    "onanieren",
    "orgasmus",
    "penis",
    "penner",
    "pimmel",
    "pimpern",
    "pinkeln",
    "pisse",
    "pissen",
    "pisser",
    "popel",
    "poppen",
    "porno",
    "puff",
    "quatsch",
    "reudig",
    "rosette",
    "saugen",
    "schabracke",
    "scheiss",
    "scheissdreck",
    "scheisse",
    "scheissekopf",
    "scheissen",
    "scheisser",
    "scheisskerl",
    "scheisskopf",
    "scheiße",
    "schiesser",
    "schlampe",
    "schnackeln",
    "schnoodle noodle",
    "schwanz",
    "schwanzlutscher",
    "schweinebacke",
    "schweinehund",
    "schwuchtel",
    "schwuchtl",
    "shaisa",
    "sheisse",
    "sohn einer hündin",
    "spasti",
    "spießig",
    "spinnen",
    "spinner",
    "spinnst",
    "teufel",
    "tittchen",
    "titten",
    "trottel",
    "verdammt",
    "verdammte scheiße",
    "verdammter",
    "verdammter Scheiß",
    "verfluchter",
    "verpiss dich",
    "verrückter mann",
    "vollidiot",
    "vollpfosten",
    "vollscheißen",
    "volltrottel",
    "vögeln",
    "was zum teufel",
    "was zur hölle",
    "weichei",
    "wichse",
    "wichsen",
    "wichser",
    "witzbold",
    "zicke",
    "zur holle mit dir",
)
val badItian = arrayOf(
    "Madonna",
    "Madonna avvelenata",
    "Madonna bastarda",
    "Madonna bocchinara",
    "Madonna impalata",
    "Madonna infiammata",
    "Madonna maiala",
    "Madonna mignotta",
    "Madonna puttana",
    "Madonna schifosa",
    "Madonna strega",
    "Madonna svergognata",
    "Madonna troia",
    "Madonna zoccola",
    "Vai a vendere il culo",
    "a pecorina",
    "abcdiet",
    "accidenti",
    "accidenti ",
    "affanculo",
    "alla cazzo di cane",
    "alla pecorina",
    "allupato",
    "amico del cazzo",
    "ammucchiata",
    "anabootcampdiet",
    "anale",
    "andare a puttane",
    "arrapato",
    "arrusa",
    "arruso",
    "assatanato",
    "avere la faccia come il culo",
    "avere un culo così grande",
    "bacha ma culo",
    "bafangu chooch",
    "bagasce",
    "bagascia",
    "bagascione",
    "bagassa",
    "bagnarsi",
    "baldracca",
    "baldraccacce",
    "baldraccaccia",
    "baldracche",
    "baldraccona",
    "baldraccone",
    "balle",
    "bariledimerda",
    "bastardacce",
    "bastardacci",
    "bastardaccia",
    "bastardaccio",
    "bastardamadonna",
    "bastarde",
    "bastardi",
    "bastardo",
    "bastardona",
    "bastardone",
    "bastardoni",
    "battere",
    "battona",
    "battone",
    "bbwpit",
    "belino",
    "biga",
    "bimbominkia",
    "bocchinara",
    "bocchinare",
    "bocchinari",
    "bocchinaro",
    "bocchini",
    "bocchino",
    "bofilo",
    "boiata",
    "bordello",
    "brinca",
    "brutto cornuto",
    "brutto figlio di puttana bastardo",
    "brutto stronzo",
    "bucaiolo",
    "budellodidio",
    "budiùlo",
    "buona donna",
    "busone",
    "bustadipiscio",
    "cacaminchia",
    "cacare",
    "cacasotto",
    "cacata",
    "cacca",
    "caciocappella",
    "cadavere",
    "cagacazzo",
    "cagaminchia",
    "cagare",
    "cagasotto",
    "cagata",
    "cagna",
    "cammello",
    "canacciodidio",
    "canagliadidio",
    "caned'allah",
    "caned'eva",
    "canedidio",
    "cappella",
    "carciofo",
    "carità",
    "carogna",
    "caronya",
    "casci",
    "cavolate",
    "cavolo",
    "cazzacci",
    "cazzaccio",
    "cazzaro",
    "cazzata",
    "cazzate",
    "cazzetti",
    "cazzetto",
    "cazzi",
    "cazzimma",
    "cazzissimo",
    "cazzo",
    "cazzo di merda",
    "cazzo in culo",
    "cazzo madre di dio",
    "cazzo si",
    "cazzona",
    "cazzone",
    "cazzoni",
    "cazzuta",
    "cazzute",
    "cazzuti",
    "cazzutissimo",
    "cazzuto",
    "ce l’hai piccolo",
    "ce un cibirut",
    "cesso",
    "che cavolo",
    "che cavolo.",
    "che cazzo",
    "che cazzo fai?",
    "che cazzo ne so",
    "che culo",
    "che due coglioni",
    "che due palle",
    "che palle",
    "che te pozzino ammazza",
    "checca",
    "checche",
    "chi cazzo sei tu?",
    "chiappa",
    "chiavare",
    "chiavata",
    "chiavate",
    "chiavatona",
    "chiavatone",
    "chissenefrega",
    "chissenefrega?",
    "ci sei cascato come una pirla",
    "ciolla",
    "ciolle",
    "ciornia",
    "ciospo",
    "ciucciamelo",
    "ciucciami il cazzo",
    "ciucciapalle",
    "cogliona",
    "coglionaggine",
    "coglionare",
    "coglionata",
    "coglionate",
    "coglionatore",
    "coglionatrice",
    "coglionatura",
    "coglionature",
    "coglionazzi",
    "coglionazzo",
    "coglioncelli",
    "coglioncello",
    "coglioncini",
    "coglioncino",
    "coglione",
    "coglioneria",
    "coglionerie",
    "coglioni",
    "col cavolo",
    "coprofago",
    "coprofilo",
    "cornuti",
    "cornuto",
    "cornutoilpapa",
    "cozza",
    "cozzo",
    "credoana",
    "cretinetti",
    "cretino",
    "cristod'undio",
    "cristodecapitato",
    "cristoincroce",
    "culattina",
    "culattone",
    "culattoni",
    "culi",
    "culo",
    "culona",
    "culone",
    "curnut",
    "dare un calcio nel culo a qualcuno",
    "deficiente",
    "di merda",
    "dietaabc",
    "dietaana",
    "dietaanabootcamp",
    "dietabootcamp",
    "dietadell'abc",
    "dio Fottuto",
    "dio bastardo",
    "dio boia",
    "dio cane",
    "dio cangurello",
    "dio dannato",
    "dio fa",
    "dio infame",
    "dio lupo",
    "dio maiale",
    "dio merda",
    "dio merdoso",
    "dio mona",
    "dio poj",
    "dio povero",
    "dio santo",
    "dio schifoso",
    "dio serpente",
    "dio sorcio",
    "dio stronzo",
    "dio verme",
    "dio zozzo",
    "diobastardo",
    "diobestia",
    "diobestiazza",
    "dioboia",
    "diocan",
    "diocane",
    "diocannaiolo",
    "diocapra",
    "diocoglione",
    "diocomunista",
    "diocrasto",
    "diocristo",
    "dioculattone",
    "diofarabutto",
    "diofascista",
    "diofinocchio",
    "dioflagellato",
    "dioimpestato",
    "dioimpiccato",
    "dioladro",
    "diolebbroso",
    "diolobotomizzato",
    "diolurido",
    "diomaiale",
    "diomaledetto",
    "diomerda",
    "diominchione",
    "dionegro",
    "dioporco",
    "diopoveraccio",
    "diopovero",
    "diorotto",
    "diorottoinculo",
    "diorutto",
    "diosbudellato",
    "dioschifoso",
    "dioseppellito",
    "dioserpente",
    "diostracane",
    "diostramerda",
    "diostronzo",
    "diosventrato",
    "dioverme",
    "ditalini",
    "ditalino",
    "dito al",
    "dove cazzo vai?",
    "duro",
    "e che cazzo",
    "essere un culo",
    "fa cagare",
    "fa schifo",
    "faccia a culo",
    "faccia di culo",
    "faccia di merda",
    "facciadaculo",
    "facciadimerda",
    "fanculo",
    "fare una sega",
    "fare unaŠ",
    "fatti i cazzi tuoi",
    "fatti una pugnetta",
    "fava",
    "femminuccia",
    "fica",
    "ficata",
    "ficate",
    "fiche",
    "fichetta",
    "fichette",
    "fichetti",
    "fichetto",
    "ficona",
    "ficone",
    "figa",
    "figata",
    "figate",
    "fighe",
    "fighetta",
    "fighette",
    "fighetti",
    "fighetto",
    "figliadicane",
    "figliadimignotta",
    "figliadiputtana",
    "figliaditroia",
    "figlidicani",
    "figlidimignotta",
    "figlidiputtana",
    "figliditroia",
    "figliedicani",
    "figliedimignotta",
    "figliediputtana",
    "figlieditroia",
    "figlio di buona donna",
    "figlio di mignotta",
    "figlio di puttana",
    "figlio di troia",
    "figlio un cane",
    "figliodicane",
    "figliodimignotta",
    "figliodiputtana",
    "figlioditroia",
    "figona",
    "figone",
    "figoni",
    "figura di merda",
    "finocchi",
    "finocchio",
    "fongoul",
    "formaggio",
    "fottere",
    "fottersi",
    "fottiti",
    "fottuta",
    "fottute",
    "fottuti",
    "fottutissima",
    "fottutissime",
    "fottutissimi",
    "fottutissimo",
    "fottuto",
    "fracicone",
    "frega un cazzo",
    "fregna",
    "frocetto",
    "froci",
    "frociara",
    "frociaro",
    "frociarola",
    "frociarolo",
    "frocio",
    "frocione",
    "frocioni",
    "frocissimo",
    "froscio",
    "fucker",
    "fumato il cervello",
    "fuori come un balcone",
    "garibaldi",
    "gesùcristaccio",
    "gesùesorcizzato",
    "gesùhandicappato",
    "gesùimpasticcato",
    "gesùmalandato",
    "gesùradioattivo",
    "gesùsieropositivo",
    "gesùstordito",
    "gesùzozzo",
    "gnocca",
    "gnocche",
    "goldone",
    "gran’ disgraziato",
    "grilletto",
    "guanto",
    "guardone",
    "heyyyyy",
    "i coglioni",
    "incazzare",
    "incazzarsi",
    "incazzata",
    "incazzate",
    "incazzati",
    "incazzatissima",
    "incazzatissime",
    "incazzatissimi",
    "incazzatissimo",
    "incazzato",
    "incazzato nero",
    "incoglionirsi",
    "inculare",
    "inculata",
    "inculate",
    "infrociato",
    "ingoio",
    "intro culo di mammata",
    "ir budello di tu ma’",
    "l'arte bolognese",
    "latrin",
    "leccacazzi",
    "leccaculi",
    "leccaculo",
    "leccafica",
    "leccafiga",
    "leccafighe",
    "leccami il culo",
    "leccami la figa",
    "leccapalle",
    "lecchino",
    "levati dai coglioni",
    "li mortacci tua",
    "lofare",
    "loffa",
    "loffare",
    "lui è proprio un bischero",
    "lui è un coglione",
    "lumaca",
    "madonna santa",
    "madonnaassassinata",
    "madonnacane",
    "madonnaimpestata",
    "madonnaisterica",
    "madonnalurida",
    "madonnamaiala",
    "madonnamongoloide",
    "madonnanegra",
    "madonnaputtana",
    "madonnaschiava",
    "madonnastregaccia",
    "madonnasudicia",
    "madonnasuicida",
    "madonnasurgelata",
    "madonnatroia",
    "madonnaviolentata",
    "mafankulo",
    "maiala",
    "manache",
    "mangia la minchia",
    "mangia merda",
    "mangia merde e morte",
    "manico",
    "mannaggia",
    "mannaggia tua",
    "mannaggiacristo",
    "mannaggiadio",
    "mannaggiailbattesimo",
    "mannaggiailclero",
    "mannaggiaisanti",
    "mannaggial'arcangelo",
    "mannaggialabibbia",
    "mannaggialadiocesi",
    "mannaggialamadonna",
    "mannaggialaputtana",
    "mannaggiapadrepio",
    "mannaggiasangiuseppe",
    "ma’ va te ne a fanculo",
    "merda",
    "merdacce",
    "merdaccia",
    "merdamalcagata",
    "merdata",
    "merdate",
    "merde",
    "merdina",
    "merdine",
    "merdolina",
    "merdoline",
    "merdona",
    "merdone",
    "merdosa",
    "merdose",
    "merdosi",
    "merdoso",
    "mezza sega",
    "mezzasega",
    "mezzeseghe",
    "mi stai facendo incazzare",
    "micio",
    "mignotta",
    "mignotte",
    "minchia",
    "minchiadura",
    "minchiaduro",
    "minchiata",
    "minchiate",
    "minchie",
    "minchione",
    "minchioni",
    "miserabili pezzo di merda",
    "mona",
    "mone",
    "mongoloide",
    "monta",
    "montare",
    "mortacci tua",
    "mussa",
    "nave scuola",
    "negra",
    "negraccia",
    "negraccio",
    "negro",
    "negrona",
    "negrone",
    "nel culo",
    "nerchia",
    "nessuno mi unfungulo",
    "non hai capito una sega",
    "non me ne importa",
    "non mi rompere i coglioni",
    "nudo",
    "oddio",
    "padulo",
    "palle",
    "palloso",
    "patacca",
    "patonza",
    "patonze",
    "pecorina",
    "perché cazzo non mi rispondi?",
    "pesce",
    "pezzo di merda",
    "picio",
    "pigliacazzi",
    "pigliainculo",
    "pincare",
    "pinnolone",
    "pipa",
    "pippone",
    "pipì",
    "pirla",
    "pisciare",
    "pisciasotto",
    "pisciata",
    "pisciatina",
    "pisciato",
    "pisciatona",
    "piscio",
    "pisciona",
    "piscione",
    "piscioni",
    "pisello",
    "pistola",
    "pistolotto",
    "pomiciare",
    "pompa",
    "pompinara",
    "pompinare",
    "pompinari",
    "pompinaro",
    "pompini",
    "pompino",
    "porca",
    "porca madonna",
    "porca miseria",
    "porca paletta",
    "porca puttana",
    "porca troia",
    "porca vacca",
    "porcamadonna",
    "porcaputtana",
    "porco",
    "porco Iddio",
    "porco cane",
    "porco dio",
    "porco due",
    "porco giuda",
    "porco zio",
    "porcodidio",
    "porcodio",
    "porcoilclero",
    "porcoilsignore",
    "posso leccare il tua figa?",
    "potta",
    "prendere per il culo",
    "prete",
    "pro-ana",
    "pro-anoressia",
    "pro-bulimia",
    "pro-ed",
    "pro-ednos",
    "pro-mia",
    "proana",
    "proanoressia",
    "probulimia",
    "proed",
    "proednos",
    "promia",
    "pugnetta",
    "pugnette",
    "puppa",
    "puppamela",
    "puppamelo",
    "puppami",
    "puppare",
    "puppe",
    "puttana",
    "puttana la Madonna",
    "puttanacce",
    "puttanaccia",
    "puttanaeva",
    "puttanaio",
    "puttanamadonna",
    "puttanata",
    "puttanate",
    "puttane",
    "puttanella",
    "puttanelle",
    "puttaniere",
    "puttanieri",
    "puttano",
    "puttanona",
    "puttanone",
    "quaglia",
    "quando cazzo torni?",
    "raspone",
    "rasponi",
    "recchione",
    "regina",
    "ricchione",
    "ricchioni",
    "rincoglionire",
    "rincoglionito",
    "rizzacazzi",
    "rizzarsi",
    "rompere i miei coglioni",
    "rompere il culo a qualcuno",
    "rompiballe",
    "rompicazzi",
    "rompicazzo",
    "rompicoglioni",
    "rompipalle",
    "rotta in culo",
    "rottinculo",
    "rotto nel culo",
    "ruffiano",
    "santo cazzo madre di cristo",
    "sbattere",
    "sbattersi",
    "sbocchinare",
    "sbocchinato",
    "sbocchiniamolo",
    "sbora",
    "sborra",
    "sborrare",
    "sborrata",
    "sborrate",
    "sborrato",
    "sborratona",
    "sborro",
    "sborrone",
    "sbrodolata",
    "sburra",
    "sburrare",
    "sburro",
    "scassacazzo",
    "scassacoglioni",
    "scassaminchia",
    "scazzare",
    "scazzata",
    "scazzate",
    "scazzati",
    "scazzato",
    "schifoso",
    "scopare",
    "scopata",
    "scopate",
    "scoregge",
    "scoreggia",
    "scorreggiare",
    "scungio",
    "secchione",
    "sega",
    "segaiolo",
    "segars",
    "seghe",
    "segone",
    "sei diventato pazza?",
    "sei diventato pazzo?",
    "sei duro come il muro",
    "sei impazzita?",
    "sei impazzito?",
    "sei pazza?",
    "sei pazzo?",
    "sei scemo",
    "sei stupido",
    "sei un cretino",
    "sei un deficiente",
    "sei un idiota",
    "sei un rompicoglioni",
    "sei una sfigata",
    "sei una testa di cazzo",
    "sei uno stronzo",
    "sembri un peni",
    "sfacim e merde",
    "sfiga",
    "sfigati",
    "sfigato",
    "signorebastardo",
    "slinguare",
    "slinguata",
    "smandrappata",
    "smerdare",
    "soccia",
    "socmel",
    "sorca",
    "spagnola",
    "spompinare",
    "spompinata",
    "spompinato",
    "spompiniamolo",
    "sputtanare",
    "sta puttana",
    "sti cazza",
    "sticchio",
    "stronza",
    "stronzata",
    "stronzate",
    "stronzetta",
    "stronzette",
    "stronzetti",
    "stronzetto",
    "stronzi",
    "stronzina",
    "stronzine",
    "stronzini",
    "stronzino",
    "stronzino/a",
    "stronzo",
    "stronzo/a",
    "stronzoli",
    "stronzolo",
    "stronzomalcagato",
    "stronzona",
    "stronzone",
    "stronzoni",
    "strunzo",
    "suca!",
    "succhiacazzi",
    "succhiamelo",
    "succhiami",
    "succhiaminchia",
    "succhiapalle",
    "succhione",
    "sveltina",
    "sverginare",
    "tarzanelli",
    "tarzanello",
    "tenere qualcuno per le palle",
    "terrone",
    "testa di cazzo",
    "testa di cazzo.",
    "testa di minchia",
    "tetta",
    "tette",
    "tettina",
    "tettine",
    "tettona",
    "tettone",
    "thinspiration",
    "thinspo",
    "ti ammazzo",
    "ti corro in culo",
    "ti sei bevuto",
    "tirare",
    "topa",
    "troia",
    "troiacce",
    "troiaccia",
    "troiamadonna",
    "troie",
    "troietta",
    "troiette",
    "troio",
    "troiona",
    "troioncella",
    "troioncelle",
    "troione",
    "trombare",
    "trombata",
    "trombatona",
    "tu ma’ piscia in piedi",
    "tu piezza di merda",
    "tua mamma bocchinara",
    "uccello",
    "un pompino",
    "vacca",
    "vaccamadonna",
    "vada a bordo",
    "vaffanculo",
    "vaffanculo a chi t'è morto",
    "vaffonculo",
    "vai a cacare",
    "vai a cagare",
    "vai a farti fottere",
    "vai a quel paese",
    "vai all’inferno",
    "vangare",
    "vattela a pigliare in culo",
    "va’ a cacare",
    "va’ a farti fottere",
    "venire",
    "zinne",
    "zio cantante",
    "zoccola",
    "zoccole",
    "zuia",
    "a fanabla"
)
val badSpanish = arrayOf(
    "Puta madre",
    "a tomar por saco",
    "anda a cagar",
    "apestar",
    "bastardo",
    "basura",
    "bicho",
    "burro",
    "cabron",
    "cabrón",
    "cacorro",
    "cagar",
    "calientapollas",
    "capullo",
    "cara de culo",
    "cara de monda",
    "carajo",
    "chapero",
    "chichi",
    "chimba",
    "chingar",
    "chocho",
    "chupame la polla",
    "chupamedias",
    "chupamela",
    "chupar",
    "chúpame la pija",
    "cipote",
    "coger",
    "cojonazos",
    "cojones",
    "come mierda y muere",
    "coño",
    "culiao",
    "culo",
    "de puta madre",
    "estúpido",
    "follar",
    "forro",
    "gilipollas",
    "gonorrea",
    "guarra",
    "hijo de perra",
    "hijo de puta",
    "hijueputa",
    "hostia",
    "huevo",
    "huevos",
    "huevón",
    "idiota",
    "imbécil",
    "jode",
    "joder",
    "joder ",
    "joto",
    "jódete",
    "la concha de tu madre",
    "la hostia",
    "la madre que te parió",
    "lame botas",
    "loco",
    "los cojones",
    "maldito",
    "malparido",
    "mamahuevo",
    "mamón",
    "marica",
    "maricon",
    "mariconazo",
    "maricón",
    "mariquita",
    "me cago en la hostia",
    "me cago en ti",
    "mierda",
    "mongolo",
    "métetelo por el culo",
    "nabo",
    "no me jodas",
    "no me jodás",
    "no seas gilipollas",
    "pajero",
    "payaso",
    "pelos de los huevos",
    "pelotas",
    "pelotudo",
    "pendejo",
    "percanta",
    "perro",
    "pichacorta",
    "pinche",
    "piruja",
    "polla",
    "pollas en vinagre",
    "puta",
    "puto",
    "que te den",
    "que te jodan",
    "qué cabrón",
    "qué te jodan",
    "rabo",
    "raja",
    "soplapollas",
    "tarado",
    "tonto",
    "tonto del culo",
    "tontopollas",
    "trompada",
    "un putero",
    "verga",
    "vete a la mierda",
    "vete a la verga",
    "vete al demonio",
    "vete al infierno",
    "zorra",
    "zunga",
    "a tomar por culo"
    )