package city.zouitel.database.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import city.zouitel.database.model.Media.Companion.TABLE_NAME
import city.zouitel.database.utils.Constants.DEFAULT_BOOLEAN
import city.zouitel.database.utils.Constants.DEFAULT_NUM
import city.zouitel.database.utils.Constants.DEFAULT_TXT
import city.zouitel.database.utils.Constants.ID
import city.zouitel.database.utils.Constants.URI
import city.zouitel.database.utils.Constants.UUID
import city.zouitel.database.utils.Constants.VIDEO

/**
 * Represents a media item (either an image or a video) stored in the local database.
 *
 * This data class is mapped to a database table named [TABLE_NAME] using Room persistence library.
 * It contains information about the media file, including its unique identifier, type, and storage uri.
 *
 * @property id The primary key for the media item. It's auto-generated by the database.
 * @property uid A unique identifier (UUID) for the media item. This can be used for cross-referencing with other systems or services.
 * @property isVideo A boolean flag indicating whether the media item is a video (true) or an image (false).
 * @property uri The URI (Uniform Resource Identifier) representing the storage location of the media file.
 */
@Entity(TABLE_NAME)
data class Media(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(ID, defaultValue = DEFAULT_NUM) val id: Long,
    @ColumnInfo(UUID, defaultValue = DEFAULT_TXT) val uid: String,
    @ColumnInfo(VIDEO, defaultValue = DEFAULT_BOOLEAN) val isVideo: Boolean,
    @ColumnInfo(URI, defaultValue = DEFAULT_TXT) val uri: String
) {
    companion object {
        const val TABLE_NAME = "media_table"
    }
}